name: Generate Commits, PRs & Issues

on:
  workflow_dispatch:
    inputs:
      total_commits:
        description: "Jumlah total commit"
        required: true
        default: "150"
      total_days:
        description: "Jumlah hari pembagian commit (misal 365 = 1 tahun)"
        required: true
        default: "365"
      total_prs:
        description: "Jumlah pull request"
        required: true
        default: "10"
      total_issues:
        description: "Jumlah issue"
        required: true
        default: "10"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git identity
        run: |
          git config user.name "uwakmusang4-rgb"
          git config user.email "236301556+uwakmusang4-rgb@users.noreply.github.com"

      - name: Generate distributed commits
        env:
          TOTAL_COMMITS: ${{ github.event.inputs.total_commits }}
          TOTAL_DAYS: ${{ github.event.inputs.total_days }}
          GIT_AUTHOR_NAME: "uwakmusang4-rgb"
          GIT_COMMITTER_NAME: "uwakmusang4-rgb"
          GIT_AUTHOR_EMAIL: "236301556+uwakmusang4-rgb@users.noreply.github.com"
          GIT_COMMITTER_EMAIL: "236301556+uwakmusang4-rgb@users.noreply.github.com"
        run: |
          mkdir -p logs
          git pull origin main || true
          COMMITS_PER_DAY=$((TOTAL_COMMITS / TOTAL_DAYS))
          START_DATE=$(date -d "$TOTAL_DAYS days ago" +%Y-%m-%d)

          echo "Membuat $TOTAL_COMMITS commit selama $TOTAL_DAYS hari..."
          for ((day=0; day<TOTAL_DAYS; day++)); do
            commit_date=$(date -d "$START_DATE +$day days" +%Y-%m-%d)
            for ((i=1; i<=COMMITS_PER_DAY; i++)); do
              echo "Commit ke-$i pada $commit_date" >> logs/commit_$day.txt
              git add logs/commit_$day.txt
              GIT_COMMITTER_DATE="$commit_date 12:00:00" GIT_AUTHOR_DATE="$commit_date 12:00:00" git commit -m "Commit $i on $commit_date" || true
            done
          done

          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }} HEAD:main

      - name: Create pull requests
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          TOTAL_PRS=${{ github.event.inputs.total_prs }}
          echo "=== Membuat $TOTAL_PRS Pull Request ==="
          for i in $(seq 1 $TOTAL_PRS); do
            branch="pr-branch-$i-$(date +%s)"
            git checkout -B $branch
            echo "File PR $i dibuat" > logs/pr_$i.txt
            git add logs/pr_$i.txt
            git commit -m "Add file for PR $i" || true
            git push -f https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }} HEAD:$branch
            gh pr create --title "Pull Request #$i" --body "Generated automatically via workflow" --base main --head $branch || echo "PR $i sudah ada"
          done
          git checkout main

      - name: Create issues
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          TOTAL_ISSUES=${{ github.event.inputs.total_issues }}
          echo "=== Membuat $TOTAL_ISSUES Issue ==="
          for i in $(seq 1 $TOTAL_ISSUES); do
            gh issue create --title "Issue #$i" --body "Auto generated issue $i via workflow" || echo "Gagal membuat issue $i"
          done
        run: |
          TOTAL_DAYS=${{ github.event.inputs.total_days }}
          TOTAL_COMMITS=${{ github.event.inputs.total_commits }}
          COMMITS_PER_DAY=$((TOTAL_COMMITS / TOTAL_DAYS))
          echo "commits_per_day=$COMMITS_PER_DAY" >> $GITHUB_OUTPUT
          echo "total_days=$TOTAL_DAYS" >> $GITHUB_OUTPUT

      - name: Generate commits
        run: |
          mkdir -p logs
          COMMITS_PER_DAY=${{ steps.calc.outputs.commits_per_day }}
          TOTAL_DAYS=${{ steps.calc.outputs.total_days }}
          echo "Total hari: $TOTAL_DAYS"
          echo "Commit per hari: $COMMITS_PER_DAY"
          for d in $(seq 0 $((TOTAL_DAYS-1))); do
            DATE=$(date -d "$d days ago" +"%Y-%m-%dT12:00:00")
            for c in $(seq 1 $COMMITS_PER_DAY); do
              echo "Commit $c on $DATE" >> logs/commit_$DATE.txt
              git add logs/commit_$DATE.txt
              git commit -m "Auto commit $c on $DATE" --date="$DATE"
            done
          done

      - name: Push commits
        run: |
          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }} main

      - name: Create pull requests
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          TOTAL_PRS=${{ github.event.inputs.total_prs }}
          for i in $(seq 1 $TOTAL_PRS); do
            branch="pr-branch-$i"
            git checkout -b $branch
            echo "Pull Request $i" >> logs/pr_$i.txt
            git add logs/pr_$i.txt
            git commit -m "Add file for PR $i"
            git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }} HEAD:$branch
            gh pr create --title "Pull Request #$i" --body "Auto PR generated" --base main --head $branch || true
          done
          git checkout main

      - name: Create issues
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          TOTAL_ISSUES=${{ github.event.inputs.total_issues }}
          for i in $(seq 1 $TOTAL_ISSUES); do
            gh issue create --title "Issue #$i" --body "Auto-generated issue #$i for contribution activity"
          done
          echo "Setiap hari akan ada $COMMITS_PER_DAY commit"

          for ((day=0; day<TOTAL_DAYS; day++)); do
            for ((c=0; c<COMMITS_PER_DAY; c++)); do
              DATE="$(date -d "${YEAR}-01-01 +${day} days" +'%Y-%m-%dT%H:%M:%S')"
              echo "Commit ${c} on day ${day} (${DATE})" >> logs/activity_log.txt
              git add logs/activity_log.txt
              git commit -m "Commit ${c} on day ${day}" --date="${DATE}"
            done
          done

          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main

      - name: Create pull requests
        run: |
          for i in $(seq 1 $TOTAL_PRS); do
            branch="pr-branch-$i"
            git checkout -b $branch
            echo "Pull Request $i" >> logs/pr_$i.txt
            git add logs/pr_$i.txt
            git commit -m "Add file for PR $i"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:$branch
            gh pr create --title "Pull Request #$i" --body "Auto PR generated" --base main --head $branch || true
          done
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Create issues
        run: |
          for i in $(seq 1 $TOTAL_ISSUES); do
            gh issue create --title "Issue #$i" --body "Auto-generated issue #$i for contribution activity"
          done
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Summary
        run: |
          echo "✅ Completed ${TOTAL_COMMITS} commits"
          echo "✅ Created ${TOTAL_PRS} pull requests"
          echo "✅ Opened ${TOTAL_ISSUES} issues"
